inputs:
  app:
    git_url: "https://github.com/Bhanuvadlamudi/testapp"
    init_file: "test.py"

  provider: 
    access_key: "AKIAIXNBKMUYYIGZPIIA"
    secret_key: "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"
    region: "us-east-1"
  resources:
    -
      name: "deploy"
      ami: "ami-0ac019f4fcb7cb7e6"
      key_name: "hello.pem"
      instance_type: "t2.micro"
