---
- hosts: all
  become: True
  remote_user: ubuntu
  gather_facts: False
  tasks:
    - name: Update linux
      become: True
      become_method: sudo
      remote_user: ubuntu
      raw: apt update  && apt install -y python3 python3-pip

    - name: "install nginx"
      become: True
      apt: name=nginx state=present
    
    -
      name: "install flask"
      pip: name=flask state=present
      become: True
    
    - 
      name: "Install git"
      apt: name=git state=present


    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent
    
    #- 
    #  git: 
    #    dest: /src/iac-cm
    #    repo: "https://github.com/Bhanuvadlamudi/iac-cm"
    #  name: "Pull from git"
    #  update: True
    #  version: master
    - 
      name: create webapps directory
      action: file dest=/src/iac-cm state=directory

    -
      name: copy web app files
      action: template src=test.py dest=/src/iac-cm/test.py

    - name : "run flask app"
      become: True
      become_method: sudo
      remote_user: ubuntu
      shell: "nohup python3 /src/iac-cm/test.py &"

    -
      name: create nginx site config
      action: template src=flask.conf dest=/etc/nginx/sites-available/flask.conf
      notify:
        - restart nginx
    - 
      name: link nginx config
      action: file src=/etc/nginx/sites-available/flask.conf dest=/etc/nginx/sites-enabled/flask.conf state=link
  
  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
      become: True
      become_method: sudo

