---
- hosts: all
  become: True
  remote_user: ubuntu
  gather_facts: False
  tasks:
  
    - name: Update linux
      become: True
      become_method: sudo
      remote_user: ubuntu
      raw: apt-get update  && apt-get install -y python python-pip python-tk

    - name: "install nginx"
      become: True
      become_method: sudo
      apt: name=nginx state=present
           
    - 
      name: "Install git"   
      apt: name=git state=present

 #   - name: "Configure nginx"
 #     include_tasks: nginx.yaml

    - name: "Deploy app"
      include_tasks: test.yaml

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
      become: True
      become_method: sudo


  
    

  

   