  - 
    name: remove default nginx site
    action: file path=/etc/nginx/sites-enabled/default state=absent

  -
    name: "create nginx site config"
    action: file src=/src/testapp/nginx.conf dest=/etc/nginx/sites-available/nginx.conf state=hard
    notify:
      - restart nginx
    
  - 
    name: link nginx config
    action: file src=/etc/nginx/sites-available/nginx.conf dest=/etc/nginx/sites-enabled/nginx.conf state=link
  
 