  - 
    name: remove default nginx site
    action: file path=/etc/nginx/sites-enabled/default state=absent

  -
    name: "create nginx site config"
    action: file src=nginx.conf dest=/etc/nginx/sites-available/nginx.conf state=hard
    notify:
      - restart nginx
    
  - 
    name: link nginx config
    action: file src=/etc/nginx/sites-available/flask.conf dest=/etc/nginx/sites-enabled/flask.conf state=link
  
  - name: restart nginx
    action: service name=nginx state=restarted 
    become: True
    become_method: sudo