- git:
    accept_hostkey: 'yes'
    clone: 'yes'
    dest: /src/testapp/
    repo: https://github.com/Bhanuvadlamudi/testapp
    update: 'no'
    version: master
  name: clone git repository
- become: 'True'
  become_method: sudo
  name: run flask app
  remote_user: ubuntu
  shell: nohup python3 /src/testapp/test.py &
